### ISSUE TITLE
La imagen de ckan-distribuible no existe en docker hub

### ISSUE THREAD

**Issue by manujas** [datosgobar/portal-andino#1]
Estuve probando el portal, muy bueno!!!

El último paso del instructivo en el *README* indica un docker run linkeando los tres contenedores pero el nombre de la imagen que está en el comando no existe en *docker hub*.

El comando
```shell
$ docker run -d --link pg-ckan:db --link solr-ckan:solr -p 80:80 -p 8800:8800 --name app-ckan datosgobar/ckan-distribuilble:latest
```

El error 
```shell
$ docker run -d --link pg-ckan:db --link solr-ckan:solr -p 80:80 -p 8800:8800 --name app-ckan datosgobar/ckan-distribuilble:latest
Unable to find image 'datosgobar/ckan-distribuilble:latest' locally
Pulling repository docker.io/datosgobar/ckan-distribuilble
docker: Error: image datosgobar/ckan-distribuilble:latest not found.
See 'docker run --help'.

```

Buscando en el docker hub de datosGobAr encontré dos posibles. `datagobar/ckan` y `datagobar/app-ckan` con la segunda logré hacer andar el portal. 

El comando que usé:
```shell
$ docker run -d --link pg-ckan:db --link solr-ckan:solr -p 80:80 -p 8800:8800 --name app-ckan datosgobar/appckan:latest
```

No se si será la imagen correcta.

**Comment by iheredia** [comment]
¡Hola, @manujas!

Buen comienzo de semana y gracias por abrirnos el issue. Valoramos un montón la ayuda.

Te contamos: cuando empezamos el desarrollo del proyecto, el nombre de la imagen era `ckan-distribuilble`. Después, optamos por un nombre un poco mas facil de escribir pero se nos pasó corregir el Readme de instalación.

El nombre de la imagen final es el mismo que encontraste por tu cuenta: `app-ckan`.

Ya corregimos el Readme en [este commit](https://github.com/datosgobar/portal-andino/commit/4635af6c59b310cf82e033e3a5e43e8dcd8ce693).

¡Muchas gracias por colaborar!

Escribinos siempre que necesites.

<br>
Buena semana,
<br><br>
El equipo de Datos Argentina.
