### ISSUE TITLE
Integración de certificados ssl y habilitación de conexiones seguras

### ISSUE THREAD

**Issue by chdigiorno** [datosgobar/portal-andino#104]
Facilitar la integración con certificados ssl para poder habilitar conexiones en modo https.

**Comment by poligarcia** [comment]
@lalo73 cuando puedas, podrás agregar una docu que explique cómo instalar un nginx en el Host de Andino y configurarlo para usar SSL con Andino como backend, incluyendo la redirección ?

Deberíamos incluir los pasos para reconfigurar Andino para que no tome el puerto 80, ya que lo tomará el host.
