### ISSUE TITLE
Analizar migrar a CKAN 2.7/2.8

### ISSUE THREAD

**Issue by lalo73** [datosgobar/portal-andino#112]
Analizar migracion a CKAN 2.7/2.8

Ver la documentacion de Ckan sobre migraciones entre versiones.
Ver que cambios necesitamos hacer para pasar a la nueva version
- Migraciones de base de datos
- Que los plugins sigan funcionando
- Nuevos servicios (ej: RQ)
- Viejos servicios

Verificar que la migracion entre la actual y 2.8 no rompa la aplicacion si ya esta instalada.

**Comment by poligarcia** [comment]
Vamos a ir a 2.7.4
