### ISSUE TITLE
Creación de sysadmin requiere email

### ISSUE THREAD

**Issue by chdigiorno** [datosgobar/portal-andino#131]
A partir de CKAN 2.7 el comando `sysadmin add` del plugin `ckan` requiere recibir el email del usuario admin (ver ckan/ckan#3600).

Modificar documentación y scripts de deploy administración para solicitar el valor.

Hay una implementacion de https://github.com/datosgobar/portal-andino/commit/591d569e85bc6fa895d33d496f7f06fdc5661637 solo deja pasar el usuario pero no el email.

Faltaria dejar que el usuario defina el email del admin.
Se debe verificar que pase los dos valores y actualizar la documentacion

**Comment by lalo73** [comment]
Cerrado en  https://github.com/datosgobar/portal-andino/commit/591d569e85bc6fa895d33d496f7f06fdc5661637
