### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Wingman2** [datosgobar/portal-andino#2]
Agregar la opción para que se inserte automáticamente el javascript en todas las paginas, solo pasando el id correspondiente.

**Comment by iheredia** [comment]
¡Hola, @Wingman2!

Buen comienzo de semana y gracias por abrirnos el issue. Valoramos un montón la ayuda.

Te contamos que tenemos en mente agregar esta funcionalidad al proyecto. Si bien la idea es sencilla, la implementación no es tan trivial. Requiere agregar un campo nuevo dentro de los formularios de configuración, persistir el id ingresado, diferenciar entre ids de google analytics y de google tag manager y finalmente insertarlo en el template base. 

No obstante, es una tarea con prioridad y que va a ser implementada en breve. 
Estate atento a la actividad del repo.

Buena semana,
El equipo de Datos Argentina.

**Comment by iheredia** [comment]
Hola @Wingman2 

Te cuento que ya contamos con analytics incorporados al portal. La diferencia con tu pedido es que decidimos que todos los portales tengan el mismo código de seguimiento para poder trackear la actividad de todos en conjunto. 

Saludos
