### ISSUE TITLE
Usar travis para generar la imagen de dockerhub

### ISSUE THREAD

**Issue by lalo73** [datosgobar/portal-andino#31]
Ver implementacion en datos.gob.ar

La imagen de dockerhub debe generarse desde el build de travis, sólo si el build fue exitoso

**Comment by poligarcia** [comment]
Esto no corresponde a portal-base?

**Comment by lalo73** [comment]
en realidad creo que aplicaria a los tres repositorios, los tres deberian pasar por travis primero

**Comment by lalo73** [comment]
Incluido en el pull-requets: https://github.com/datosgobar/portal-andino/pull/27
