### ISSUE TITLE
Error al logearme con un usuario comun creado según la documentación

### ISSUE THREAD

**Issue by avilaton** [datosgobar/portal-andino#48]
Instalé andino siguiendo las instrucciones básicas y luego cree un usuario admin que puede logearse sin problemas. Al intentar crear un usuario común, también parece que tengo éxito desde la consola pero ese usuario no consigue logearse. Como hago para ver los logs?

**Comment by iheredia** [comment]
Hola avilaton 

El portal genera muchos tipos de logs. En este caso particular, los logs que te servirían para entender que está pasando son los que genera apache. Los podes ver entrando al contenedor de docker del portal via `docker exec -it andino /bin/bash` y una vez adentro los logs de apache se encuentran en `/var/log/apache2/error.log`.

Por otro lado, el plugin de ckan que estamos usando no tiene buen soporte para multiples usuarios. Este es un issue que venimos atacando desde hace un tiempo y vamos a tener las modificaciones listas para la semana que viene. 

Si necesitas otra cosa, avisanos y vamos a tratar de ayudarte.

Saludos, 
Ignacio

**Comment by avilaton** [comment]
Ok, muchas gracias, luego de abrir este ticket me di cuenta de que quizás prefieran usar el repositorio del `theme` para estos asuntos ya que cualquier fix estaría ahi.
Saludos y cierro esto por ahora.
