### ISSUE TITLE
Error al cargar un recurso

### ISSUE THREAD

**Issue by avilaton** [datosgobar/portal-andino#49]
Pasos para reproducir:
- Instalar andino,
- Crear un usuario admin,
- Logearse a andino son ese usuario,
- Crear una organización,
- Crear un dataset, asociar un recurso CSV, publicar,
- Intentar visualizar el recurso

En a vista de este dataset se reporta un error que lee
```
 Esta vista de recurso no está disponible al momento. Haga click aquí para más información.

Could not load view: DataProxy returned an error (Data transformation failed. error: An error occured while connecting to the server: DNS lookup failed for URL: http://localhost/dataset/dd65ae53-2122-4ffa-a1da-b05a18837d57/resource/d6f00b46-21a0-43f5-a3db-f2fcf1d780f4/download/parajes.csv)
```
Adjunto screenshot.
![screencapture-localhost-dataset-prueba-resource_data-fee290bd-4389-4539-b4ad-8d9b3e45ac72-1498139007039](https://user-images.githubusercontent.com/2209022/27437294-2f2668ba-5738-11e7-8eea-f5087ea6c0e5.png)

PD: el link de descargar SI funciona.

**Comment by iheredia** [comment]
Hola avilaton. 

Te vamos a pedir un poco mas de info para terminar de entender que está pasando con este error. 
En particular nos interesa saber qué sistema operativo y version estas usando, qué version de docker y docker-compose tenés instaladas y si este error lo estás teniendo con todos los recursos que intentaste cargar o no.

Saludos,
Ignacio

**Comment by avilaton** [comment]
```
▶ docker --version
Docker version 17.03.1-ce, build c6d412e                                                                                                                                                                  
▶ docker-compose --version
docker-compose version 1.8.0, build unknown
▶ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
Lo intenté solo con recursos CSV, 3 veces con el mismo resultado.
La config que usé es esta
```
NGINX_HOST_PORT=80
EMAIL=avila.gas+andino@gmail.com
HOST=localhost
DB_USER=andino_db_user
DB_PASS=anino_db_pass
STORE_USER=andino_datastore_user
STORE_PASS=andino_datastore_pass

python ./install.py --error_email "$EMAIL" --site_host="$HOST" \
    --database_user="$DB_USER" --database_password="$DB_PASS" \
    --datastore_user="$STORE_USER" --datastore_password="$STORE_PASS"
```

**Comment by lalo73** [comment]
Buenos días, podrías correr estos comandos y luego volver a intentar subir el mismo recurso:

`docker-compose -f dev.yml exec portal /etc/ckan_init.d/change_site_url.sh "http://localhost:8080"`
`docker-compose -f dev.yml restart`

Gracias

**Comment by avilaton** [comment]
Ejecuté lo solicitado y volvi a subir el dataset para ahora recibir otro error distinto:
![screencapture-localhost-dataset-asdasdas-resource_data-d430667e-2c2f-40fe-8dc6-de06b8d9b529-1499115160604](https://user-images.githubusercontent.com/2209022/27807614-5c311752-6042-11e7-996e-ae482624b45d.png)
