### ISSUE TITLE
Link de descargar recurso apunta a la vista

### ISSUE THREAD

**Issue by avilaton** [datosgobar/portal-andino#50]
Este es un :bug: menor pero uno de los links que dicen `descargar recurso` apunta a la misma página en la que está el recurso y no causa la descarga.
![screenshot from 2017-06-22 10-54-43](https://user-images.githubusercontent.com/2209022/27437673-5fe364e8-5739-11e7-8da3-dc897000fda5.png)

**Comment by pilimayora** [comment]
@avilaton se movió este issue a los repos de los themes - tanto de datos.gob.ar como de andino.
Gracias por notar este bug!!
