### ISSUE TITLE
Error al correr el scipt install.py del portal-andino

### ISSUE THREAD

**Issue by regonzalom** [datosgobar/portal-andino#57]
Estimados,

Estoy siguiendo la guía http://portal-andino.readthedocs.io/es/stable/setup/usage/#instalacion-de-andino para instalar el portal (ya tengo instalados y funcionando las dependencias).

Ejecuto el comando...

```
python ./install.py --error_email $EMAIL --site_host=$HOST \
    --database_user=$DB_USER --database_password=$DB_PASS \
    --datastore_user=$STORE_USER --datastore_password=$STORE_PASS 
```

Obtengo la siguiente salida ... 

![screenshot from 2017-07-16 04 54 19](https://user-images.githubusercontent.com/1321510/28245626-9be58c36-69e1-11e7-87dd-28dfeef60bc7.png)

Investigué bastante... probé ejecutar el script con python3, reinstalar mis librerías de python pero no consigo sortear este error ¿Como creen que pueda solucionarlo? 

Desde ya muchas gracias y Slds.,
Gon

**Comment by iheredia** [comment]
Hola @regonzalom 

Tenes un problema de permisos. Puede ser porque el dueño de la carpeta `/etc/portal` no es el mismo usuario con el cual estas corriendo el script de instalación, o porque necesites permisos de sudo.
La misma captura que subiste dice explicitamente "Permiso denegado".

![28245626-9be58c36-69e1-11e7-87dd-28dfeef60bc7](https://user-images.githubusercontent.com/4714590/28270285-44bf5540-6adb-11e7-98e2-b381f8c6c0ad.png)


Saludos

**Comment by regonzalom** [comment]
Ignacio,

Muchas gracias por tu respuesta funcionó como like a charm! Te molesto ahora porque tengo otros mensajes de error...

![screenshot from 2017-07-19 02 48 35](https://user-images.githubusercontent.com/1321510/28352250-ac5bbcec-6c2b-11e7-959b-c24c3af1706c.png)

¿Cómo la ves?¿me dedico a otra cosa :-)?

Gracias,
Slds.,

**Comment by iheredia** [comment]
Hola Gonzalo

En base a lo que hablamos por mail cierro el issue.

Saludos
