### ISSUE TITLE
Problema luego de reiniciar

### ISSUE THREAD

**Issue by avilaton** [datosgobar/portal-andino#63]
Hola equipo,
lo instalamos en un concejo deliberante y funciona piola. La VPS fue reiniciada y ahora andino se trancó. nginx está arriba pero devuelve un 502 y los logs muestran, entre otras cosas:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
```
me parece que está relacionado con como lo instalamos la primera vez o algo asi. 
Alguna idea?
Gracias

**Comment by iheredia** [comment]
Hola @avilaton 

Necesitamos mas info. ¿Como lo instalaste? ¿Que documentación seguiste?
¿Configuraste a mano apache? 

Saludos

**Comment by avilaton** [comment]
Hola, 
lo instalé con la instalación simplificada, pasé los datos que necesitaba y funcionó hasta que alguien reinició la VPS. No configuré apache a mano, yaiks.
Lo instalamos para que evaluaran usarlo y se pusieron a subir cosas como si fuera definitivo...
Saludos y gracias por contestar tan rápido.
