### ISSUE TITLE
Error en instalación - Debian 8.x jessie

### ISSUE THREAD

**Issue by kabeza** [datosgobar/portal-andino#66]
Hola. Buen dia
Les escribo porque intenté realizar la instalación en un Debian 8.x recien instalado.

- Setié las variables
- Baje el install.py
- Ejecute el script
Anduvo todo bien hasta que tiró el siguiente error, y no tengo experiencia con python, docker, etc.

![imagen_934](https://user-images.githubusercontent.com/274856/31397450-74b90c72-adbc-11e7-9700-418b0d41e208.jpg)

Algun consejo? Debo ejecutar el install.py nuevamente?

Gracias

**Comment by kabeza** [comment]
Como pueden ver en el mensaje de error 
_"Error starting userland proxy"_ , 
estoy detrás de un proxy corporativo muy restringido, no se si eso tenga que ver...

También veo _listen 0.0.0.0:25 bind: address already in use_ y en ningun momento me pide un IP ni la variable HOST que setié previamente

**Comment by juja** [comment]
Hola:

Entre otras cosas, se instala un contenedor con un servidor de mail(postfix), seguramente el Debian trae preinstalado uno. Desinstalalo o paralo y reintentá.

Saludos

**Comment by kabeza** [comment]
Hola @juja 
Tuve que remover exim4 y apache2 para que la instalación finalmente sea exitosa

Tenés idea donde puedo sacar el usuario y clave de admin del CKAN para comenzar a cargar datasets, etc. y/o cambiar template?

Muchas gracias

**Comment by juja** [comment]
Probá con lo siguiente, parado en el directorio donde corriste install.py:

`docker-compose -f latest.yml exec portal /etc/ckan_init.d/add_admin.sh mi_nuevo_usuario_admin
`

mi_nuevo_usuario_admin es el nombre del usuario. Después logueate en http://ip_del_server/ingresar .

Acá tenés mucha info: http://portal-andino.readthedocs.io/es/master/setup/usage/

Saludos

**Comment by kabeza** [comment]
Solo para saber, ese comando de docker composer será lo mismo que hacer lo siguiente?
(estoy viendo algo de docker, como acceder a los containers, bash del container, y paster, que es lo que sale en la documentacion de ckan)

```
sudo docker ps
sudo docker exec -it andino bash
paster --plugin=ckan sysadmin add admin --config=/etc/ckan/default/production.ini
```
Gracias nuevamente

**Comment by juja** [comment]
No lo probé pero imagino que si porque es lo que ejecuta add_admin.sh y corre bajo el contexto del mismo contenedor.

Sludos
