### ISSUE TITLE
Contenido mixto cuando se carga el sitio con https y usuarios

### ISSUE THREAD

**Issue by kabeza** [datosgobar/portal-andino#69]
Buenas
Finalmente pudimos instalar andino y crear un usuario sysadmin

1.Al cargar el sitio, obtenemos por consola un error debido a contenido mixto (https, http) y quisieramos saber (segun el adjunto) en que archivo deberiamos cambiar la configuracion o que archivo editar para poder cambiar esas urls que estan dando este inconveniente

![imagen_964](https://user-images.githubusercontent.com/274856/31671939-8524435e-b331-11e7-9bbc-62f725e9e915.jpg)

2. Al ingresar con el usuario sysadmin, hemos intentado crear un usuario desde el mismo panel de ckan pero no sabemos como es el procedimiento. Debe llegarle al usuario un email con los datos y la clave? O debemos setear la clave con paster?

Desde ya muchas gracias

**Comment by pilimayora** [comment]
Hola @kabeza 
Cómo estás?

1. Necesitamos pedirte más detalles para poder ayudarte. Cómo configuraste SSL? Estamos trabajando sobre la documentación para configurar un Andino para que use HTTPS asumiendo que tienen un certificado. Mientras tanto, te podemos ayudar si nos brindás más info sobre las modificaciones que hiciste para configurar SSL. 

2. Pudiste ver la guía de uso?
https://github.com/datosgobar/portal-andino-theme/blob/master/docs/guia_uso_portal_andino.md 
Ahí hay una sección sobre usuarios y permisos. Si tu pregunta va por otro lado, está también la documentación sobre usuarios (donde usa comandos con paster): http://portal-andino.readthedocs.io/es/master/setup/usage/#crear-un-nuevo-usuario-de-andino.

**Comment by kabeza** [comment]
Hola @pilimayora 
Perdon por la tardanza en responder, pero hemos tenido inconvenientes en la VM de Andino con Docker, contenedores que se reinician frecuentemente y dado que no poseemos mucha experiencia en ese sentido, estamos dando vueltas intentando solucionar eso
Con respecto a tus consultas

1. El sitio esta en un subdominio. Frente al subdominio esta un nginx que tiene los certificados, pero hacia dentro de la red donde se encuentra el subdominio, va todo por http, por eso una vez que solucionemos lo de los contenedores, tenemos que ver como forzar a CKAN para que la site url o algo asi sea todo con https

2. Si, creo que vamos a manejarnos de ahora en mas con paster, etc.

Muchas gracias
Saludos
