### ISSUE TITLE
Error 502 bad Gateway al cargar el portal

### ISSUE THREAD

**Issue by regonzalom** [datosgobar/portal-andino#71]
Estimados,

Luego de estar funcionando correctamente obtenemos este mensaje al cargar el portal.

`502 Bad Gateway

nginx/1.11.9`

No estoy muy familiarizad con la tecnología Docker (estoy empezando a hacerlo) ¿Hay alguna forma de hacer debug u obtener más info para solucionar el caso (yo no monté este servidor Andino pero heredo el matenimiento)?

Slds.,
Gon

**Comment by regonzalom** [comment]
Estimados,

Encuentro que este problema se porque el docker andino (entiendo que es el que tiene el servidor apache) se reinicia sin cesar... alguna idea de como puedo ponerlo en funcionamiento?

Desde ya muchas gracias,
Gon

**Comment by regonzalom** [comment]
@devartis @datosgobar

**Comment by juja** [comment]
Buen día:

Me acaba de pasar lo mismo, acá la solución:

### TL;DR
* Baja todos los contenedores o el servicio docker
* Cambiate a root(sudo su)
* Busca el archivo apache2.pid dentro de /var/lib/docker( find -name apache2.pid)
* Borrá el archivo/os encontrados
* Inicia el servicio/contenedores

### Causa

El contenedor "andino" se reinicia constantemente porque:
* Tiene la restart policy always, lo que hace que cuando se cae se reinicie automaticamente.
* Apache arranca, verifica que hay otra instancia corriendo, porque encuentra su PID file(/var/run/apache2/apache2.pid) y se cierra. Por el punto anterior, se vuelve a levantar y queda en un bucle. 

Esto puede pasar cuando no se cierra correctamente y apache no logra borrar su PID file.
Fuera de un contenedor, */run* es un sistema de archivos temporal(*tmpfs*), no conserva los cambios cuando se reinicia el server por lo que, en caso de falla del servidor, el archivo se pierde. Esto mismo no pasa dentro de un contenedor docker por ende apache no inicia hasta que no se borre este archivo.

Luego es necesario buscar el archivo y eliminarlo, se encontrará bajo del directorio aufs/diff donde se guardan los cambios realizados al fs original. Este caso es usando [AUFS](https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/) no sé si pasará lo mismo con otro storage driver.


Saludos

**Comment by regonzalom** [comment]
@juja muchas gracias efectivamente es lo que sucedió. Recreando los Dockers se pudo solucionar.


Un saludo,
Gon
