### ISSUE TITLE
Error en el usuario colabordor

### ISSUE THREAD

**Issue by juanehernandez** [datosgobar/portal-andino#72]
Estando logueado como colaborador, realizando distintas acciones se desloguea y redirigue al inicio.
Casos probados:
-En el primer paso de la creacion de un dataset, al hacer clic en "continuar y agregar recursos"
-Al agregar un recurso, haciendo clic en "Publicar"

En ambos casos, la url que quedo en el navegador es la sigueinte: http://andino.datos.gob.ar/?__no_cache__=True

**Comment by bishalkc** [comment]
I get the same behavior only on the first login as a administrator
