### ISSUE TITLE
Agregar reglas de validación de campos

### ISSUE THREAD

**Issue by juanehernandez** [datosgobar/portal-andino#76]
Agregar validaciones a los siguientes campos.

Título, descripción e imagen del portal -> Título:
-Validar que haya sido completado
-Validar longitud mínima: 9 caracteres
-Validar longitud máxima 100 caracteres
Texto de error en carga:"El nombre debería tener al menos 9 caracteres."
Aclaración debajo debajo el inpunt: "Por favor, no superes los 100 caracteres."
Agregar asterisco de obligatorio

Título, descripción e imagen del portal -> Descripción del portal
-Validar que haya sido completado
-Validar longitud mínima: 30 caracteres
-Validar longitud máxima 300 caracteres
Aclaración debajo debajo el inpunt: "Por favor, no superes los 300 caracteres."
Agregar asterisco de obligatorio

Título, descripción e imagen del portal -> Redes sociales y contacto -> Mail de contacto:
-Validar que haya sido completado
-Validar que sea un mail
Texto de error en la carga: 
"Ingrese un email válido."
Agregar asterisco de obligatorio

Crear dataset y agregar recursos -> URL
-Bloquear la edición de la URL cuando se edita un dataset. Si es posible editarla cuando se crea.

Crear dataset y agregar recursos -> Agregar Recursos -> Título del recurso:
-Validar que haya sido completado
Agregar asterisco de obligatorio

Crear dataset y agregar recursos -> Agregar Recursos -> Descripción del recurso:
-Validar que haya sido completado
Agregar asterisco de obligatorio

**Comment by chdigiorno** [comment]
datos.gob.ar también requeriría arreglos como los de este issue?
