### ISSUE TITLE
Imposibilidad de crear vistas

### ISSUE THREAD

**Issue by juanehernandez** [datosgobar/portal-andino#78]
No se pueden crear vistas en los recursos ya que no funciona el botón(andino y datos.gob.ar). Hay dos issues creados por lo mismo: datosgobar/portal-andino-theme: Problema n.º 80 y datosgobar/portal-andino-theme: Problema n.º 103

**Comment by poligarcia** [comment]
Este issue fue resuelto en andino 2.3.0
