### ISSUE TITLE
Configurar CD para staging

### ISSUE THREAD

**Issue by lalo73** [datosgobar/portal-andino#96]
Haciendo uso del script de actualizacion y basandose en lo implementado en Series de Tiempo, implementar el Continuous Deployment al ambiente de staging, andino.datos.gob.ar.

La implementacion de staging puede ayudar en esto.

**Comment by lalo73** [comment]
Falta configurar Staging como se hizo en #94

**Comment by poligarcia** [comment]
Ya funciona el CD en staging! https://travis-ci.org/datosgobar/portal-andino/builds/367934645
