### ISSUE TITLE
Documentacion: Link a 404

### ISSUE THREAD

**Issue by jas1** [datosgobar/portal-andino#98]
Buenas es para informarles que en la pagina de documentacion:
http://portal-andino.readthedocs.io/es/master/

el link: Actualización

lleva a la siguiente URL: http://portal-andino.readthedocs.io/es/master/setup/update.md

que parece ser eliminada, tiene el siguiente mensaje: 

>         \          SORRY            /
>          \                         /
>           \    This page does     /
>            ]   not exist yet.    [    ,'|
>            ]                     [   /  |
>            ]___               ___[ ,'   |
>            ]  ]\             /[  [ |:   |
>            ]  ] \           / [  [ |:   |
>            ]  ]  ]         [  [  [ |:   |
>            ]  ]  ]__     __[  [  [ |:   |
>            ]  ]  ] ]\ _ /[ [  [  [ |:   |
>            ]  ]  ] ] (#) [ [  [  [ :===='
>            ]  ]  ]_].nHn.[_[  [  [
>            ]  ]  ]  HHHHH. [  [  [
>            ]  ] /   `HH("N  \ [  [
>            ]__]/     HHH  "  \[__[
>            ]         NNN         [
>            ]         N/"         [
>            ]         N H         [
>           /          N            \
>          /           q,            \
>         /                           \

**Comment by poligarcia** [comment]
Este issue ya fue resuelto!
